##
##    First, need to set up the deployhost with
##    needed software, services and settings
##



- hosts: myDeployhost
  tasks:

    - debug: msg="**** BEGIN SETUP  ****"

    - include_role:
        name: xtoph_deploy
      vars: 
        xtoph_deploy_action: "setup"
      when: xtoph_deploy_cmd == "setup" or
            xtoph_deploy_cmd == "setup+"

    - debug: msg="**** END SETUP  ****"



##
##    Second, for libvirt based platform hosts
##    we need to install software, services and settings
##    on the remote hosts (not on the deploy host)
##



- hosts: myLibvirtHosts
  gather_facts: no
  tasks:

    - debug: msg="**** BEGIN SETUP LIBVIRT ****"

    - include_role:
        name: xtoph_deploy
      vars:
        xtoph_deploy_action: "preprocess"
      when: xtoph_deploy_cmd == "setup" or
            xtoph_deploy_cmd == "setup+"

    - include_role:
        name: xtoph_deploy
      vars:
        xtoph_deploy_action: "deploy"
      when: xtoph_deploy_cmd == "setup" or
            xtoph_deploy_cmd == "setup+"

    - name:  "Gathering facts for libvirt host"
      setup:

    - include_role:
        name: xtoph_deploy
      vars:
        xtoph_deploy_action: "setup-libvirt"
      when: xtoph_deploy_cmd == "setup" or
            xtoph_deploy_cmd == "setup+"

    - debug: msg="**** END SETUP LIBVIRT ****"



##
##    Next, execute undeploy activities
##
##     NOTE: hosts may (or may not) exist, 
##           majority of tasks run as 'delegate_to'
##           and so we don't gather_facts
##



- hosts: myMachines
  gather_facts: no 
  tasks:

    - debug: msg="**** BEGIN UNDEPLOY ****"

    - include_role:
        name: xtoph_deploy
      vars:
        xtoph_deploy_action: "undeploy"
      when: xtoph_deploy_cmd == "undeploy" or
            xtoph_deploy_cmd == "redeploy"

    - debug: msg="**** END UNDEPLOY ****"



##
##     Before we start deploying systems, we
##     need to ensure certain basics are configured.
##     Run the 'deploy_preprocess' to:
##       - generate MAC addresses if needed
##       - add DNS entries to /etc/hosts
##       - maybe more stuff, go look!
##



- hosts: myMachines
  gather_facts: no
  tasks:

    - debug: msg="**** BEGIN PREPROCESS  ****"

    - include_role:
        name: xtoph_deploy
      vars:
        xtoph_deploy_action: "preprocess"
      when: xtoph_deploy_cmd == "deploy" or
            xtoph_deploy_cmd == "setup+" or
            xtoph_deploy_cmd == "redeploy"

    - debug: msg="**** END PREPROCESS  ****"



##
##     Deploy systems in batches of 'serial'
##
##     NOTE: for same reasons listed above
##           don't gather_facts 
##
##     NOTE: 'serial: #' limits concurrent 
##           deployments and resolves problems
##           related to disk space and i/o
##           limits
##



- hosts: myMachines
  gather_facts: no 
  serial: 3 
  tasks:

    - debug: msg="**** BEGIN DEPLOY  ****"

    - include_role:
        name: xtoph_deploy
      vars:
        xtoph_deploy_action: "deploy"
      when: xtoph_deploy_cmd == "deploy" or
            xtoph_deploy_cmd == "setup+" or
            xtoph_deploy_cmd == "redeploy"

    - debug: msg="**** END DEPLOY  ****"



##
##    All nodes should be deployed
##    So proceed to hook-in additional playbooks (ie: workshops)
##
##    NOTE: For this project, we just deploy and forget
##          No post processing at this time, but this is 
##          left to serve as an example
##




#- import_playbook: playbooks/rhel8-workshop.yml
#  when: xtoph_deploy_cmd == "deploy" or 
#        xtoph_deploy_cmd == "setup+" or 
#        xtoph_deploy_cmd == "redeploy" or 
#        xtoph_deploy_cmd == "workshop"

