##
## CUSTOM PLATFORM PROFILES
##

xtoph_config_platform:

  baremetal:

    platform_profile:

      platform: "baremetal"

      vm:
        name: "{{ xtoph_vars.clustername }}_{{ inventory_hostname }}"

      kickstart:
        description: "hints to where installers can find devices"
        netdev:  "{{ h_netDEV | default('ens3') }}"
        blkdev:  "{{ h_blkDEV | default('sda') }}"

      network:
        default:
          description:       "default baremetal network parameters"
          ip:                "{{ h_pubIP  }}"
          mac:               "{{ h_pubMAC| default('') }}"
          basedomain:        "{{ workshop_vars.network_basedomain }}"
          network:           "{{ workshop_vars.network_network    }}"
          netmask:           "{{ workshop_vars.network_netmask    }}"
          broadcast:         "{{ workshop_vars.network_broadcast  }}"
          prefix:            "{{ workshop_vars.network_prefix     }}"
          gateway:           "{{ workshop_vars.network_gateway    }}"
          nameserver:        "{{ workshop_vars.network_nameserver }}"
          timeserver:        "{{ workshop_vars.network_timeserver }}"
          fqdn:              "{{ workshop_extras.network_fqdn     }}"
  
      storage:
        default:
          description:       "default baremetal storage parameters"
          noop:              "noop value to force list for lookup"

